[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wlkatapython-dev"
version = "0.1.0"
description = "WLKATA-Mirobot/E4/MT4/MS4220 Multiple robotic arm control"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "DS"}
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyserial",
]

[tool.hatch.build.targets.wheel]
packages = ["src/wlkatapython"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "pytest-xdist>=3.6.1",
]
docs = [
    "sphinx>=7.0",
    "sphinx-rtd-theme",
]




